remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
title: Homepage - Dejan Demonjić
description: Bookmark this to keep an eye on my project updates!
